//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMHostController.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMHostInfo
    {
        public VMHostInfo()
        {
            this.VMInfoes = new HashSet<VMInfo>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string IPAddress { get; set; }
        public string URL { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<VMInfo> VMInfoes { get; set; }
    }
}
